with-expecter: true
packages:
    simple-file-processor/internal/db:
      config:
      interfaces:
        Database:
          config:
            filename: "mock_db.go"
            dir: "internal/mocks/mockdb"
            mockname: "{{.InterfaceName}}"
            outpkg: "mockdb"
        GormDB:
          config:
            filename: "mock_gorm_db.go"
            dir: "internal/mocks/mockdb"
            mockname: "{{.InterfaceName}}"
            outpkg: "mockdb"
    simple-file-processor/internal/lib:
      config:
      interfaces:
        CommandExecutor:
          config:
            filename: "mock_command_executor.go"
            dir: "internal/mocks/mocklib"
            mockname: "{{.InterfaceName}}"
            outpkg: "mocklib"
        MetadataExtractor:
          config:
            filename: "mock_metadata_extractor.go"
            dir: "internal/mocks/mocklib"
            mockname: "{{.InterfaceName}}"
            outpkg: "mocklib"
    simple-file-processor/internal/tasks:
      config:
      interfaces:
        Client:
          config:
            filename: "mock_client.go"
            dir: "internal/mocks/mocktasks"
            mockname: "{{.InterfaceName}}"
            outpkg: "mocktasks"
        Task:
          config:
            filename: "mock_task.go"
            dir: "internal/mocks/mocktasks"
            mockname: "{{.InterfaceName}}"
            outpkg: "mocktasks"
        Resizer:
          config:
            filename: "mock_resizer.go"
            dir: "internal/mocks/mocktasks"
            mockname: "{{.InterfaceName}}"
            outpkg: "mocktasks"