// Code generated by mockery v2.52.2. DO NOT EDIT.

package mocktasks

import mock "github.com/stretchr/testify/mock"

// Task is an autogenerated mock type for the Task type
type Task struct {
	mock.Mock
}

type Task_Expecter struct {
	mock *mock.Mock
}

func (_m *Task) EXPECT() *Task_Expecter {
	return &Task_Expecter{mock: &_m.Mock}
}

// Enqueue provides a mock function with no fields
func (_m *Task) Enqueue() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Enqueue")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Task_Enqueue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Enqueue'
type Task_Enqueue_Call struct {
	*mock.Call
}

// Enqueue is a helper method to define mock.On call
func (_e *Task_Expecter) Enqueue() *Task_Enqueue_Call {
	return &Task_Enqueue_Call{Call: _e.mock.On("Enqueue")}
}

func (_c *Task_Enqueue_Call) Run(run func()) *Task_Enqueue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Task_Enqueue_Call) Return(_a0 error) *Task_Enqueue_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Task_Enqueue_Call) RunAndReturn(run func() error) *Task_Enqueue_Call {
	_c.Call.Return(run)
	return _c
}

// NewTask creates a new instance of Task. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTask(t interface {
	mock.TestingT
	Cleanup(func())
}) *Task {
	mock := &Task{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
