// Code generated by mockery v2.52.2. DO NOT EDIT.

package mocklib

import (
	io "io"

	mock "github.com/stretchr/testify/mock"
)

// FileSystem is an autogenerated mock type for the FileSystem type
type FileSystem struct {
	mock.Mock
}

type FileSystem_Expecter struct {
	mock *mock.Mock
}

func (_m *FileSystem) EXPECT() *FileSystem_Expecter {
	return &FileSystem_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: path
func (_m *FileSystem) Create(path string) (io.WriteCloser, error) {
	ret := _m.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 io.WriteCloser
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (io.WriteCloser, error)); ok {
		return rf(path)
	}
	if rf, ok := ret.Get(0).(func(string) io.WriteCloser); ok {
		r0 = rf(path)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.WriteCloser)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(path)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FileSystem_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type FileSystem_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - path string
func (_e *FileSystem_Expecter) Create(path interface{}) *FileSystem_Create_Call {
	return &FileSystem_Create_Call{Call: _e.mock.On("Create", path)}
}

func (_c *FileSystem_Create_Call) Run(run func(path string)) *FileSystem_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *FileSystem_Create_Call) Return(_a0 io.WriteCloser, _a1 error) *FileSystem_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *FileSystem_Create_Call) RunAndReturn(run func(string) (io.WriteCloser, error)) *FileSystem_Create_Call {
	_c.Call.Return(run)
	return _c
}

// NewFileSystem creates a new instance of FileSystem. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewFileSystem(t interface {
	mock.TestingT
	Cleanup(func())
}) *FileSystem {
	mock := &FileSystem{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
